### PR TITLE
Accordion variants

### PR DESCRIPTION
**Pull request by yleaxeman**

### CODE REVIEW

**Review by proand — CHANGES_REQUESTED** [review]
The "library-item" should be split up in three, so that I can copy the code for the one I want.

`.fhi-accordion-flush-alt` should be in its own file in folder `src/blocks`, and should be proper BEM, and is `-alt` necessary?

...and update changelog

**Comment by yleaxeman** [comment]
> The "library-item" should be split up in three, so that I can copy the code for the one I want.
> 
> `.fhi-accordion-flush-alt` should be in its own file in folder `src/blocks`, and should be proper BEM (if possible...), and is `-alt` necessary?
> 
> ...and update changelog

Actually, maybe the third variant should be `.accordion-flush--alt` (or `--alternative`)? Might be confusing with one `.fhi-` prefixed variant in the mix...

**Comment by proand** [comment]
> > The "library-item" should be split up in three, so that I can copy the code for the one I want.
> > `.fhi-accordion-flush-alt` should be in its own file in folder `src/blocks`, and should be proper BEM (if possible...), and is `-alt` necessary?
> > ...and update changelog
> 
> Actually, maybe the third variant should be `.accordion-flush--alt` (or `--alternative`)? Might be confusing with one `.fhi-` prefixed variant in the mix...
I do think we should keep a hard seperation between modifications of Bootstrap, and new styles/components that are unique for FHI...

**Review by proand — APPROVED** [review]
LGTM 👍

**Pull request merged**
